# .streamlit/secrets.toml

[connections.gsheets]
spreadsheet = "https://docs.google.com/spreadsheets/d/1X52j-7c7ENN4jqL-JbYFuReDY3oz55khXa6AupgopLk/edit#gid=0"
type = """service_account"""
project_id = "ha360-202602"
private_key_id = "da5e59b314aaeaed084076cb73a9a15e7deb09ca"
private_key = """-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCtn3Oya0fyXQ7b\nnWB31CoLz/LQ7WkaWXdZflZnyzo0XLdjinDdCfJCNUcYtdXlZnRV+KQ3mqDwzqX/\n6AV0PGpMug0/dXcLTI5btP8PrP+5MyqeCy6M7rowMc7wvTculg6KB+EUeTnvtGJl\nTv55C7HNYi/E/PLJRoxb+3MguoIUda0NDMamNYKGCF6LUK3BfvSFcM8+cQOM2EjY\nCnlsk4Qbs9hyTxqsS7dewV0npjR1B/XwZcGFm8MhOXzstu8BlBOLdVq0hBIy0wij\ntCENiyM6E4gr3+CrvsjZ40jx+1ik7x9dagKXnRj0UWEbvMO+uoZU9PwHaoaa2kG2\nA5TJUfz3AgMBAAECggEADroivzSYYreABiLgRunJMz1NVGl+68xA8mdj/uPfKQfg\nSmI41pb8ZJ9OS4tI/G9nWM+BZnIISsTMkdtlcwmY3q89Zm+ZTG0O+jptFDBRdK0h\nZUx/g1bQljvzWLpEDwCNdSnb7relsW50ljFQJoZWa5xzftsR4P7J8xduGY2YcRGy\nO3U2lmA5przen1Lx+Q/iJ5rFvKcIOH2wevogxZo4SKTR7/bR96bli4c1IL64JgvS\nijDC5IL55kpOPEe7NhHuRsECijDzSvTamVz5N1DmdiNZjoZU1dBVcbnAy+CtaUil\nh1IYBMDNJ/SGr1OTvO8rd+p89JUxnFG4ho9zcOchYQKBgQDtKrKV28L4Yg4aTz1m\naBlmzeTsBpDtiqNjcHn1XZd5aigKjoWjkHBkpJlFID62ifiIM8Sf9fZSPGPRXB/n\nfLL5MbomXsvFfqU7DZ1rDXdzq2A5Fafz8y57XBmn8ggbCV/g2DRFi24a5hqt3Zrp\nC1O1nYUzGtIXQmv09gpkYMxjZwKBgQC7aPx5S3I3S7It79WCki9LhMFKoVgCgTh9\nTC6Tc77YOjjWvdoMBHgG8/ZrkYUEB+PKe94B3Xqvsh9f1EmAjSl618LKFbtc30a8\nxHtx4HrxgFdP6+b+55MNzKom16IheNWHAcAbgZO2CtIMW+pb/V1PZm8lZGoZKNgt\n4eoVi0Ov8QKBgAXN+bj5O/hgTgAO2G3dNmHxwByWvI1Ty1PvuMxskfyCwKAhhNvP\n+TA9ZxLuCxrknZSXz8QqfPDeUYMaQh2kS60Vrnyp7UrUIq8jUisAlV/bXeuHwCiU\nVxrl0iruHYyr2hDiucTJ+NPntddziQsTH+VeCZiKm4G+Om4wZ2i1hcsZAoGBAJkq\nkr2nVa+vo+47R2qxgwnbdAZEmyNg7QQqkR5dyKn725xWCbEsrdQw60K66dWDhT5l\nweoQU0bo8w9k9rWjqTUGxeJXpIugx7Vbd/B4IMLju3hMOrw2E0+B58ZbEdz9XrY6\nTgGtA0YSzdzf+kg4aFyOQWR0DuqFITlOm/wDl8xhAoGBALL9zIjki+5pbAIiJVen\niVGhniwTgWb4cuKSXFJzBhWmCHSOEgc3AtG2eXrZgvRkjju2JH4VXo78cCZ6s/U2\n5KwwY5YzODXS8URCnbYwS0VvhAeOHaSdajOmX6yTvwDg1C+AO+h/BcSOKMn/6ZbZ\n7zvhpZ6bfHBuryfCBM9dFwcX\n-----END PRIVATE KEY-----\n"""
client_email = "ibmha360@ha360-202602.iam.gserviceaccount.com"
client_id = "109340138593047656716"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/ibmha360%40ha360-202602.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

[passwords]
admin_password = "ha360rcs"

[url_modes]
checkin_on_key = "in-on-K3137FY1ZK"
checkin_off_key = "in-off-1EG9A4A6L4"
checkout_key = "out-9HT993O33C"